const DEFAULTS={content:{title:'O instante passa.<br><em>A imagem fica.</em>',subtitle:'Histórias reais, luz autêntica e fotografias que fazem você sentir tudo outra vez.',about:'Sou Wemerson Nascimento, fotógrafo movido por pessoas, movimento e histórias honestas. Meu trabalho combina direção cuidadosa e olhar documental para criar imagens elegantes, vivas e verdadeiramente suas.'},photos:Array.from({length:11},(_,i)=>({id:`default-${i+1}`,src:`./img/Galeria/FOTO   (${i+1}).jpeg`,title:`História ${String(i+1).padStart(2,'0')}`,category:['eventos','retratos','esportes'][i%3]})),testimonials:[{id:'t1',name:'Mariana & Lucas',event:'Ensaio de casal',quote:'Wemerson fez a gente esquecer que havia uma câmera ali. O resultado tem verdade, movimento e a nossa cara.'},{id:'t2',name:'Rafael Santos',event:'Retrato profissional',quote:'O processo foi leve, muito bem dirigido e o resultado elevou completamente a imagem do meu trabalho.'},{id:'t3',name:'Produção Lumen',event:'Cobertura de evento',quote:'Além do olhar incrível, ele tem a agilidade e a sensibilidade de quem entende o ritmo de um grande evento.'}]};
const get=(k,f)=>{try{return JSON.parse(localStorage.getItem(`wn_${k}`))||f}catch{return f}},save=(k,v)=>localStorage.setItem(`wn_${k}`,JSON.stringify(v));let photos=get('photos',DEFAULTS.photos),comments=get('testimonials',DEFAULTS.testimonials),content=get('content',DEFAULTS.content);
const toast=t=>{const el=document.querySelector('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)};
const titles={overview:'Visão geral',photos:'Portfólio',content:'Textos do site',comments:'Depoimentos'};function go(id){document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id===id));document.querySelectorAll('.sidebar nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));document.querySelector('#page-title').textContent=titles[id];document.querySelector('.sidebar').classList.remove('open');renderAll()}document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>go(b.dataset.tab));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
function renderAll(){document.querySelector('#photo-count').textContent=photos.length;document.querySelector('#comment-count').textContent=comments.length;document.querySelector('#storage-used').textContent=`${(new Blob(Object.values(localStorage)).size/1024).toFixed(0)} KB`;document.querySelector('#recent-photos').innerHTML=photos.slice(-6).reverse().map(p=>`<img src="${p.src}" alt="${p.title}">`).join('');renderPhotos();renderComments()}
function renderPhotos(){const q=document.querySelector('#photo-search').value.toLowerCase(),cat=document.querySelector('#photo-filter').value;const list=photos.filter(p=>p.title.toLowerCase().includes(q)&&(cat==='all'||p.category===cat));document.querySelector('#admin-gallery').innerHTML=list.length?list.map(p=>`<article class="photo-card"><img src="${p.src}" alt="${p.title}"><div><span><strong>${p.title}</strong>${p.category}</span><button data-delete-photo="${p.id}">Excluir</button></div></article>`).join(''):'<p>Nenhuma foto encontrada.</p>'}
function renderComments(){document.querySelector('#comments-list').innerHTML=comments.length?comments.map(c=>`<article class="comment-card"><div><strong>${c.name}</strong><span>${c.event}</span></div><blockquote>“${c.quote}”</blockquote><button data-delete-comment="${c.id}">Excluir</button></article>`).join(''):'<p>Nenhum depoimento cadastrado.</p>'}
document.querySelector('#photo-search').oninput=renderPhotos;document.querySelector('#photo-filter').onchange=renderPhotos;document.querySelector('#admin-gallery').onclick=e=>{const id=e.target.dataset.deletePhoto;if(id&&confirm('Excluir esta foto do portfólio?')){photos=photos.filter(p=>p.id!==id);save('photos',photos);renderAll();toast('Foto excluída')}};document.querySelector('#comments-list').onclick=e=>{const id=e.target.dataset.deleteComment;if(id&&confirm('Excluir este depoimento?')){comments=comments.filter(c=>c.id!==id);save('testimonials',comments);renderAll();toast('Depoimento excluído')}};
const uploadModal=document.querySelector('#upload-modal'),commentModal=document.querySelector('#comment-modal');document.querySelector('#open-upload').onclick=()=>uploadModal.showModal();document.querySelector('#open-comment').onclick=()=>commentModal.showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
const fileInput=document.querySelector('[name=files]');fileInput.onchange=()=>{document.querySelector('#file-preview').innerHTML=[...fileInput.files].map(f=>`<img src="${URL.createObjectURL(f)}" alt="Prévia">`).join('')};
const toDataUrl=file=>new Promise((resolve,reject)=>{const r=new FileReader;r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)});document.querySelector('#upload-form').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),files=[...fileInput.files];if(files.some(f=>f.size>4*1024*1024))return toast('Cada foto deve ter até 4 MB');try{const items=await Promise.all(files.map(async(f,i)=>({id:`photo-${Date.now()}-${i}`,src:await toDataUrl(f),title:files.length>1?`${fd.get('title')} ${i+1}`:fd.get('title'),category:fd.get('category')})));photos.push(...items);save('photos',photos);uploadModal.close();e.currentTarget.reset();document.querySelector('#file-preview').innerHTML='';renderAll();toast(`${items.length} foto(s) publicada(s)`) }catch(err){if(err.name==='QuotaExceededError'||String(err).includes('quota'))toast('Armazenamento cheio. Exclua fotos antigas.');else toast('Não foi possível processar a imagem')}};
document.querySelector('#comment-form').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.currentTarget);comments.push({id:`comment-${Date.now()}`,name:fd.get('name'),event:fd.get('event'),quote:fd.get('quote')});save('testimonials',comments);commentModal.close();e.currentTarget.reset();renderAll();toast('Depoimento publicado')};
const cf=document.querySelector('#content-form');cf.title.value=content.title;cf.subtitle.value=content.subtitle;cf.about.value=content.about;cf.onsubmit=e=>{e.preventDefault();content={title:cf.title.value,subtitle:cf.subtitle.value,about:cf.about.value};save('content',content);document.querySelector('#content-status').textContent='Alterações salvas ✓';toast('Site atualizado');setTimeout(()=>document.querySelector('#content-status').textContent='',2500)};
const login=document.querySelector('#login'),authenticated=sessionStorage.getItem('wn_admin')==='true';if(authenticated)login.classList.add('hidden');document.querySelector('#login-form').onsubmit=e=>{e.preventDefault();if(new FormData(e.currentTarget).get('pin')===(localStorage.getItem('wn_pin')||'2025')){sessionStorage.setItem('wn_admin','true');login.classList.add('hidden')}else document.querySelector('#login-error').textContent='PIN incorreto. Tente novamente.'};document.querySelector('#logout').onclick=()=>{sessionStorage.removeItem('wn_admin');login.classList.remove('hidden')};document.querySelector('.mobile-menu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');renderAll();
